import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SiteHeader from "./components/layouts/header/SiteHeader";
import SiteFooter from "./components/layouts/footer/SiteFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body dir="rtl" className={inter.className}>
                <SiteHeader />
                {children}
                <SiteFooter />
            </body>
        </html>
    );
}
